[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.9"
geo = "0.27.0"
geo-types = "0.7.12"
nalgebra = "0.32.3"
